function opt = featureExtractOptSet
    opt.datasetDir = './recordings/';% where you put your wav files, the filenames should be in the following formet: noteName_vowels_phonationModeOrType
    opt.featurePath = './waveData.mat'; %where you put your feature mat file
	opt.featureList={'MFCC','LPCDan','LSP','GlottalMFCCGLOAT','GlottalMFCCSTRAIGHT','GlottalMFCCLPCDan','GlottalMFCCLPCvoicebox'};
	opt.frameRate = 50;
	% opt.LPCOrder = 120;
	opt.Glottal.frameRate = 50;
	% opt.Glottal.LPCOrder = 120;
	opt.Glottal.f0Min = 80;
	opt.Glottal.f0Max = 800;
